// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rater.Data.DataContext;

#nullable disable

namespace Rater.Data.Migrations
{
    [DbContext(typeof(DBBContext))]
    partial class DBBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rater.API.Metric", b =>
                {
                    b.Property<int>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("metric_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MetricId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("SpaceId")
                        .HasColumnType("integer")
                        .HasColumnName("space_id");

                    b.HasKey("MetricId")
                        .HasName("metrics_pkey");

                    b.HasIndex(new[] { "SpaceId", "Name" }, "metrics_space_id_name_key")
                        .IsUnique();

                    b.ToTable("metrics", (string)null);
                });

            modelBuilder.Entity("Rater.API.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("participant_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParticipantId"));

                    b.Property<string>("ParticipantName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("participant_name");

                    b.Property<int>("SpaceId")
                        .HasColumnType("integer")
                        .HasColumnName("space_id");

                    b.HasKey("ParticipantId")
                        .HasName("participants_pkey");

                    b.HasIndex(new[] { "SpaceId", "ParticipantName" }, "participants_space_id_participant_name_key")
                        .IsUnique();

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("Rater.API.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rating_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RatingId"));

                    b.Property<int>("MetricId")
                        .HasColumnType("integer")
                        .HasColumnName("metric_id");

                    b.Property<DateTime?>("RatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("RateeId")
                        .HasColumnType("integer")
                        .HasColumnName("ratee_id");

                    b.Property<int>("RaterId")
                        .HasColumnType("integer")
                        .HasColumnName("rater_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int>("SpaceId")
                        .HasColumnType("integer")
                        .HasColumnName("space_id");

                    b.HasKey("RatingId")
                        .HasName("ratings_pkey");

                    b.HasIndex("MetricId");

                    b.HasIndex("RateeId");

                    b.HasIndex("SpaceId");

                    b.HasIndex(new[] { "RaterId", "RateeId", "SpaceId", "MetricId" }, "ratings_rater_id_ratee_id_space_id_metric_id_key")
                        .IsUnique();

                    b.ToTable("ratings", (string)null);
                });

            modelBuilder.Entity("Rater.API.Space", b =>
                {
                    b.Property<int>("SpaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("space_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpaceId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.HasKey("SpaceId")
                        .HasName("spaces_pkey");

                    b.HasIndex("CreatorId");

                    b.ToTable("spaces", (string)null);
                });

            modelBuilder.Entity("Rater.API.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nickname");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Rater.API.Metric", b =>
                {
                    b.HasOne("Rater.API.Space", "Space")
                        .WithMany("Metrics")
                        .HasForeignKey("SpaceId")
                        .IsRequired()
                        .HasConstraintName("metrics_space_id_fkey");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("Rater.API.Participant", b =>
                {
                    b.HasOne("Rater.API.Space", "Space")
                        .WithMany("Participants")
                        .HasForeignKey("SpaceId")
                        .IsRequired()
                        .HasConstraintName("participants_space_id_fkey");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("Rater.API.Rating", b =>
                {
                    b.HasOne("Rater.API.Metric", "Metric")
                        .WithMany("Ratings")
                        .HasForeignKey("MetricId")
                        .IsRequired()
                        .HasConstraintName("ratings_metric_id_fkey");

                    b.HasOne("Rater.API.Participant", "Ratee")
                        .WithMany("Ratings")
                        .HasForeignKey("RateeId")
                        .IsRequired()
                        .HasConstraintName("ratings_ratee_id_fkey");

                    b.HasOne("Rater.API.User", "Rater")
                        .WithMany("Ratings")
                        .HasForeignKey("RaterId")
                        .IsRequired()
                        .HasConstraintName("ratings_rater_id_fkey");

                    b.HasOne("Rater.API.Space", "Space")
                        .WithMany("Ratings")
                        .HasForeignKey("SpaceId")
                        .IsRequired()
                        .HasConstraintName("ratings_space_id_fkey");

                    b.Navigation("Metric");

                    b.Navigation("Ratee");

                    b.Navigation("Rater");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("Rater.API.Space", b =>
                {
                    b.HasOne("Rater.API.User", "Creator")
                        .WithMany("Spaces")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("spaces_creator_id_fkey");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Rater.API.Metric", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Rater.API.Participant", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Rater.API.Space", b =>
                {
                    b.Navigation("Metrics");

                    b.Navigation("Participants");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Rater.API.User", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Spaces");
                });
#pragma warning restore 612, 618
        }
    }
}
